name: paymentez_mobile
description: A new Flutter module to use the paymentez services for Android and IOS apps.
publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^3.0.10
  equatable: ^1.2.5
  meta: ^1.3.0
  font_awesome_flutter: ^8.12.0
  flutter_bloc: ^4.0.0
  path_provider: ^1.6.27
  after_layout: ^1.0.7+2
  crypto: ^3.0.0
  flutter_svg: ^0.19.3
  mask_text_input_formatter: ^1.2.1
  fluro: ^1.6.3
  flutter_kount:
    git:
      url: git://github.com/oaacelasu/flutter_kount.git
      ref: master

  cupertino_icons: ^0.1.2

flutter:
  assets:
    - assets/
    - assets/images/
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.paymentez.paymentez_mobile
    iosBundleIdentifier: com.paymentez.paymentezMobile
